/**
 * Export a committed period from the local SQLite database as Postgres SQL.
 *
 *   node scripts/pg_export.mjs ./period.db > period.sql
 *   psql "$DATABASE_URL" -f period.sql
 *
 * WHY A FILE AND NOT AN API CALL. The extract is licensed for internal use and
 * not for redistribution. A file that goes from this machine to the practice's
 * own database over psql passes through nothing else; pushing the same rows
 * through a hosted tool call would send a TSX Group extract to a third party
 * on its way there. It is also the only way to move 259 companies without
 * paying for every row twice.
 *
 * The rows come from the committed SQLite tables rather than from the parser,
 * so what lands in Postgres is what the tested commit path produced.
 */
import { DatabaseSync } from "node:sqlite";

const [dbPath] = process.argv.slice(2);
if (!dbPath) {
  console.error("usage: node scripts/pg_export.mjs <sqlite db> > period.sql");
  process.exit(2);
}
const db = new DatabaseSync(dbPath);

/** Ordered so a foreign key never precedes what it references. */
const TABLES = [
  ["periods", ["id", "label", "market_cap_as_of", "threshold_amount", "threshold_operator",
               "threshold_currency", "proximity_band_pct", "status", "revision",
               "source_file_sha256", "rule_set_version"]],
  ["companies", ["id", "canonical_name", "name_normalized", "first_seen_period_id", "status"]],
  ["company_identifiers", ["id", "company_id", "scheme", "value", "exchange", "valid_from",
                           "valid_to", "source"]],
  ["company_aliases", ["company_id", "name", "name_normalized", "alias_type",
                       "first_seen_period_id", "source"]],
  ["company_period_facts", ["period_id", "company_id", "field_key", "raw_value", "typed_value",
                            "assertion"]],
  ["company_period_field_values", ["period_id", "company_id", "field_key", "value", "source",
                                   "evidence_state", "source_period_id", "rule_version",
                                   "basis_hash", "decided_at"]],
  ["company_period_stages", ["period_id", "company_id", "stage"]],
  ["tiers", ["period_id", "company_id", "tier", "status", "footprint", "rule_set_version"]],
  ["tier_traces", ["period_id", "company_id", "ord", "rule_id", "inputs", "matched"]],
];

/**
 * jsonb and uuid columns need a cast; SQLite hands everything back as text.
 *
 * `value` is jsonb in company_period_field_values and TEXT in
 * company_identifiers, so the set is keyed by table.value where it matters:
 * casting a bare ticker to jsonb fails, because ABRA is not valid JSON.
 */
const JSON_COLUMNS = new Set([
  "typed_value", "inputs",
  "company_period_field_values.value",
  "published_period_values.value",
]);
const UUID_COLUMNS = new Set(["id", "period_id", "company_id", "first_seen_period_id",
                              "source_period_id"]);
const BOOL_COLUMNS = new Set(["matched"]);

/**
 * The publication tables are NOT exported: a period's revisions are thousands
 * of frozen rows each and they are re-made by publishing, not by copying. So
 * the period arrives as a DRAFT. Carrying status='published' across without
 * its publications would leave the periods table asserting a publication that
 * is not there, and the dashboard would read "not published" beneath a period
 * that says it is.
 */
function literal(column, value, table) {
  if (table === "periods" && column === "status") return "'draft'";
  if (table === "periods" && column === "revision") return "1";
  if (value === null || value === undefined) return "null";
  if (BOOL_COLUMNS.has(column)) return value ? "true" : "false";
  const text = String(value);
  const quoted = `'${text.replace(/'/g, "''")}'`;
  if (JSON_COLUMNS.has(`${table}.${column}`) || JSON_COLUMNS.has(column)) return `${quoted}::jsonb`;
  if (UUID_COLUMNS.has(column)) return `${quoted}::uuid`;
  return quoted;
}

console.log("-- Generated by scripts/pg_export.mjs. Exchange-derived columns originate");
console.log("-- from a TSX Group Inc. issuer extract and are for internal use only.");
console.log("-- Not for redistribution.");
console.log("-- The period arrives as a draft: publications are re-made, never copied.");
console.log("begin;");

let total = 0;
for (const [table, allColumns] of TABLES) {
  const rows = db.prepare(`select ${allColumns.join(", ")} from ${table}`).all();
  if (rows.length === 0) continue;

  // A column that is null in every row is not worth 3,626 copies of the word
  // "null": leave it out and let the column default apply.
  const columns = allColumns.filter(
    (c) => rows.some((r) => r[c] !== null && r[c] !== undefined));
  // Batched so one statement is never megabytes long. PG_EXPORT_BATCH lowers it
  // for transports that cap a single statement.
  const batchSize = Number(process.env.PG_EXPORT_BATCH ?? 200);
  for (let i = 0; i < rows.length; i += batchSize) {
    const batch = rows.slice(i, i + batchSize);
    const values = batch
      .map((r) => `(${columns.map((c) => literal(c, r[c], table)).join(", ")})`)
      .join(",\n  ");
    console.log(`insert into ${table} (${columns.join(", ")}) values\n  ${values}\n` +
                `on conflict do nothing;`);
  }
  total += rows.length;
  console.error(`  ${String(rows.length).padStart(6)}  ${table}`);
}

console.log("commit;");
console.error(`\n${total} rows written to stdout`);
