/**
 * Export a committed period from the local SQLite database as Postgres SQL.
 *
 *   node scripts/pg_export.mjs ./period.db > period.sql
 *   psql "$DATABASE_URL" -f period.sql
 *
 * WHY A FILE AND NOT AN API CALL. The extract is licensed for internal use and
 * not for redistribution. A file that goes from this machine to the practice's
 * own database over psql passes through nothing else; pushing the same rows
 * through a hosted tool call would send a TSX Group extract to a third party
 * on its way there. It is also the only way to move 259 companies without
 * paying for every row twice.
 *
 * The rows come from the committed SQLite tables rather than from the parser,
 * so what lands in Postgres is what the tested commit path produced.
 */
import { DatabaseSync } from "node:sqlite";

const [dbPath] = process.argv.slice(2);
if (!dbPath) {
  console.error("usage: node scripts/pg_export.mjs <sqlite db> > period.sql");
  process.exit(2);
}
const db = new DatabaseSync(dbPath);

/** Ordered so a foreign key never precedes what it references. */
const TABLES = [
  ["periods", ["id", "label", "market_cap_as_of", "threshold_amount", "threshold_operator",
               "threshold_currency", "proximity_band_pct", "status", "revision",
               "source_file_sha256", "rule_set_version"]],
  ["companies", ["id", "canonical_name", "name_normalized", "first_seen_period_id", "status"]],
  ["company_identifiers", ["id", "company_id", "scheme", "value", "exchange", "valid_from",
                           "valid_to", "source"]],
  ["company_aliases", ["company_id", "name", "name_normalized", "alias_type",
                       "first_seen_period_id", "source"]],
  ["company_period_facts", ["period_id", "company_id", "field_key", "raw_value", "typed_value",
                            "assertion"]],
  ["company_period_field_values", ["period_id", "company_id", "field_key", "value", "source",
                                   "evidence_state", "source_period_id", "rule_version",
                                   "basis_hash", "decided_at"]],
  ["company_period_stages", ["period_id", "company_id", "stage"]],
  ["tiers", ["period_id", "company_id", "tier", "status", "footprint", "rule_set_version"]],
  ["tier_traces", ["period_id", "company_id", "ord", "rule_id", "inputs", "matched"]],
];

/** jsonb and uuid columns need a cast; SQLite hands everything back as text. */
const JSON_COLUMNS = new Set(["typed_value", "value", "inputs"]);
const UUID_COLUMNS = new Set(["id", "period_id", "company_id", "first_seen_period_id",
                              "source_period_id"]);
const BOOL_COLUMNS = new Set(["matched"]);

function literal(column, value) {
  if (value === null || value === undefined) return "null";
  if (BOOL_COLUMNS.has(column)) return value ? "true" : "false";
  const text = String(value);
  const quoted = `'${text.replace(/'/g, "''")}'`;
  if (JSON_COLUMNS.has(column)) return `${quoted}::jsonb`;
  if (UUID_COLUMNS.has(column)) return `${quoted}::uuid`;
  return quoted;
}

console.log("-- Generated by scripts/pg_export.mjs. Exchange-derived columns originate");
console.log("-- from a TSX Group Inc. issuer extract and are for internal use only.");
console.log("-- Not for redistribution.");
console.log("begin;");

let total = 0;
for (const [table, columns] of TABLES) {
  const rows = db.prepare(`select ${columns.join(", ")} from ${table}`).all();
  if (rows.length === 0) continue;
  // Batched so one statement is never megabytes long.
  for (let i = 0; i < rows.length; i += 200) {
    const batch = rows.slice(i, i + 200);
    const values = batch
      .map((r) => `(${columns.map((c) => literal(c, r[c])).join(", ")})`)
      .join(",\n  ");
    console.log(`insert into ${table} (${columns.join(", ")}) values\n  ${values}\n` +
                `on conflict do nothing;`);
  }
  total += rows.length;
  console.error(`  ${String(rows.length).padStart(6)}  ${table}`);
}

console.log("commit;");
console.error(`\n${total} rows written to stdout`);
