-- Where a parsed upload waits between its validation report and its commit.
--
-- The report has to precede the commit -- that is the load-bearing property of
-- the quarterly refresh in docs/design/01 -- so parse and commit are two
-- requests, and the parse has to survive between them. It used to survive as a
-- file in the server's temporary directory, which works on one machine and not
-- on a platform where consecutive requests land on different instances: the
-- commit could not find the parse its own validation report had just shown.
--
-- What is held is the PARSED PAYLOAD, never the workbook. The workbook is
-- parsed and discarded inside the request that carried it, so there is still
-- no durable copy of a licensed extract anywhere. A row lives an hour.

create table upload_quarantine (
  -- 32 hex characters, generated by the server and never taken from a filename.
  id          text primary key,
  filename    text not null,
  size_bytes  integer not null,
  -- Of the WORKBOOK, which is what a committed period records as its source.
  sha256      text not null,
  payload     jsonb not null,
  uploaded_by uuid references app_users(id),
  parsed_at   timestamptz not null default now(),
  expires_at  timestamptz not null
);

create index upload_quarantine_expiry on upload_quarantine (expires_at);
